frase = input("digite uma frase ")
print(frase)
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(len(frase))
print(frase.count('a'))
print(frase.find('r'))
print(frase.isdigit())
print(frase[3])
print(frase[2:5])
palavras = frase.split()
print(palavras)
frase = frase.replace(' ', '_')
print(frase)